version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile/nginx/Dockerfile
    ports:
      - "${NGINX_HOST_PORT}:${NGINX_INTERNAL_PORT}"
    depends_on:
      bookshop_db:
        condition: service_healthy
    volumes:
      - ../../services/bookshop:/app/
    links:
      - php
    networks:
      - ${GLOBAL_NETWORK:-services}